### PR TITLE
Created ReadMeSpanish.md

### PR DESCRIPTION
**Pull request by ananthuc73**

### CODE REVIEW

**Comment by ananthuc73** [comment]
Created ReadMeSpanish.md

**Comment by hgvanpariya** [comment]
@ananthuc73 : will you also create a link in Readme.md to switch to ReadMeSpanish.md ?

**Comment by hgvanpariya** [comment]
@jfprada : agree with you ...

**Comment by hgvanpariya** [comment]
closing this PR as the translation is done via google translate ....

**Pull request closed without merging**
